### ISSUE TITLE
Error with Python 3.10 (and working in 3.9)

### ISSUE THREAD

**Issue by rennefJ** [OfflineIMAP/offlineimap3#99]
#### General informations

- system/distribution (with version):  docker with python:3-alpine image
- offlineimap version (`offlineimap -V`): 8.0.0
- Python version: 3.10

#### Logs, error
 > File "/usr/src/offlineimap3/offlineimap/imaplibutil.py", line 26, in <module>  
    import rfc6555  
  File "/usr/local/lib/python3.10/site-packages/rfc6555.py", line 19, in <module>  
    from selectors2 import DefaultSelector, EVENT_WRITE  
  File "/usr/local/lib/python3.10/site-packages/selectors2.py", line 25, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/local/lib/python3.10/collections/__init__.py)

#### Steps to reproduce the error
build the following dockerfile and run the containter:
> FROM python:3-alpine
WORKDIR /usr/src
RUN apk --no-cache add openssl wget
RUN pip3 install --no-cache-dir imaplib2 distro rfc6555 urllib3 certifi
RUN wget -nv https://github.com/OfflineIMAP/offlineimap3/archive/refs/heads/master.zip && unzip master.zip && rm master.zip && mv offlineimap3-master/ offlineimap3
WORKDIR /usr/src/offlineimap3
CMD [ "python3", "./offlineimap.py" ]

If I use the python:3.9-alpine image it works, but using the lastest python 3.10 does not work.
Searching the web for the error message I found this:
[https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections](https://stackoverflow.com/questions/69381312/in-vs-code-importerror-cannot-import-name-mapping-from-collections)
So it seems something changed from 3.9 to 3.10

**Comment by nicolas33** [comment]
This issue stands in the [selectors2 library](https://github.com/sethmlarson/selectors2). I think you should report this issue to this project where this seems not addressed.

A workaround for offlineimap could be to get the rid of the rfc6555 library. However, this could make more harm than good. I'd wait for upstream to fix this.

Users can avoid this issue by setting the [ipv6 configuration option](https://github.com/OfflineIMAP/offlineimap3/blob/master/offlineimap.conf#L665) in the configuration file.

**Comment by rennefJ** [comment]
@nicolas33 I wanted to report the issue to selectors2 repository today. Sadly the owner has archived the project. It is read-only and no issues can be created anymore. :(

**Comment by nicolas33** [comment]
Please, report this issue to the [rfc6555 repository](https://github.com/sethmlarson/rfc6555). That's the library we import which is usin the selectors2 project. Both are from the same maintainer.

**Comment by rennefJ** [comment]
@nicolas33 , I already contacted the maintainer and opened an issue.
I can happily report that he already has released an updated version (0.1.0) of rfc6555 that fixes the issue.
Tested offlineimap 8.0.0 today with python 3.10 in docker container and its working. So this issue here can be closed.
